(function(g){var window=this;var TDa=function(a,b){return g.Wb(a,b)},c6=function(a){g.En(a,"zx",g.wc());
return a},d6=function(a,b,c){g.Fa(c)||(c=[String(c)]);
g.Hn(a.o,b,c)},UDa=function(a,b){var c=[];
g.pl(b,function(a){try{var b=g.eE.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.za(b)?g.dE(b)&&c.push(a):c.push(a)},a);
return c},VDa=function(a,b){var c=UDa(a,b);
(0,g.C)(c,function(a){g.eE.prototype.remove.call(this,a)},a)},WDa=function(a){if(a.Md){if(a.Md.locationOverrideToken)return{locationOverrideToken:a.Md.locationOverrideToken};
if(null!=a.Md.latitudeE7&&null!=a.Md.longitudeE7)return{latitudeE7:a.Md.latitudeE7,longitudeE7:a.Md.longitudeE7}}return null},XDa=function(a,b,c,d){var e=new g.vn(null,void 0);
a&&g.wn(e,a);b&&g.xn(e,b);c&&g.yn(e,c);d&&g.zn(e,d);return e},e6=function(a,b){g.XE[a]=!0;
var c=g.VE();c&&c.publish.apply(c,arguments);g.XE[a]=!1},f6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.B=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.pn;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",YDa(this,a.capabilities||""),ZDa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",this.o=a.localChannelEncryptionKey||
"")},YDa=function(a,b){a.capabilities.clear();
(0,g.oe)(b.split(","),g.La(TDa,$Da)).forEach(function(b){a.capabilities.add(b)})},ZDa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},g6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},h6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},aEa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},bEa=function(a){return new g6(a)},cEa=function(a){return g.Fa(a)?(0,g.I)(a,bEa):[]},i6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},j6=function(a){return g.Fa(a)?"["+(0,g.I)(a,i6).join(",")+"]":"null"},k6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},dEa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},l6=function(a,b){return g.Ra(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},m6=function(a,b){return g.Ra(a,function(a){return h6(a,b)})},eEa=function(){var a=(0,g.gI)();
a&&VDa(a,a.o.ce(!0))},n6=function(){var a=g.jI("yt-remote-connected-devices")||[];
g.qb(a);return a},fEa=function(a){if(g.Wa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},gEa=function(a){g.iI("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.jI("yt-remote-device-id");a||(a=k6(),g.iI("yt-remote-device-id",a,31536E3));for(var b=n6(),c=1,d=a;g.Va(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=n6(),b=p6();
g.Va(a,b);g.lI()&&g.sb(a,b);a=fEa(a);if(g.Wa(a))try{g.GH("remote_sid")}catch(c){}else try{g.FH("remote_sid",a.join(","),-1)}catch(c){}},hEa=function(){return g.jI("yt-remote-session-browser-channel")},iEa=function(){return g.jI("yt-remote-local-screens")||[]},jEa=function(){g.iI("yt-remote-lounge-token-expiration",!0,86400)},kEa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(iEa(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.cn)(c,function(a){return!g.Va(b,a)})&&jEa();
g.iI("yt-remote-local-screens",a,31536E3)},lEa=function(a,b){g.iI("yt-remote-session-browser-channel",a);
g.iI("yt-remote-session-screen-id",b);var c=n6(),d=p6();g.Va(c,d)||c.push(d);gEa(c);q6()},r6=function(a){a||(g.kI("yt-remote-session-screen-id"),g.kI("yt-remote-session-video-id"));
q6();a=n6();g.$a(a,p6());gEa(a)},mEa=function(){if(!s6){var a=g.pE();
a&&(s6=new g.ZD(a))}return s6?!!s6.get("yt-remote-use-staging-server"):!1},t6=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},nEa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},u6=function(a){a.length?oEa(a.shift(),function(){u6(a)}):v6()},pEa=function(a){return"chrome-extension://"+a+w6},oEa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},v6=function(){var a=nEa();
a&&a(!1,"No cast extension found")},rEa=function(){if(qEa){var a=2,b=nEa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;oEa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",v6,c)}},sEa=function(){rEa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);u6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+w6,"//www.gstatic.com/eureka/clank"+w6])},x6=function(a,b,c){g.J.call(this);
this.F=null!=c?(0,g.A)(a,c):a;this.Fd=b;this.D=(0,g.A)(this.cL,this);this.o=!1;this.A=0;this.B=this.Ia=null;this.C=[]},y6=function(){},z6=function(a,b,c,d){this.o=a;
this.B=b;this.G=c;this.F=d||1;this.C=45E3;this.Y=new g.Ln(this);this.A=new g.Pg;this.A.setInterval(250)},uEa=function(a,b,c){a.Xj=1;
a.Ch=c6(b.clone());a.jj=c;a.D=!0;tEa(a,null)},A6=function(a,b,c,d,e){a.Xj=1;
a.Ch=c6(b.clone());a.jj=null;a.D=c;e&&(a.FF=!1);tEa(a,d)},tEa=function(a,b){a.Tk=(0,g.H)();
B6(a);a.di=a.Ch.clone();d6(a.di,"t",a.F);a.Tn=0;a.Vc=a.o.Mt(a.o.Ln()?b:null);0<a.uu&&(a.Tq=new g.Yl((0,g.A)(a.XG,a,a.Vc),a.uu));a.Y.X(a.Vc,"readystatechange",a.iV);var c=a.Ji?g.gc(a.Ji):{};a.jj?(a.Sr="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Vc.send(a.di,a.Sr,a.jj,c)):(a.Sr="GET",a.FF&&!g.ce&&(c.Connection="close"),a.Vc.send(a.di,a.Sr,null,c));a.o.Af(1)},xEa=function(a,b,c){for(var d=!0;!a.ri&&a.Tn<c.length;){var e=vEa(a,c);
if(e==C6){4==b&&(a.Dh=4,D6(15),d=!1);break}else if(e==wEa){a.Dh=4;D6(16);d=!1;break}else E6(a,e)}4==b&&0==c.length&&(a.Dh=1,D6(17),d=!1);a.Gf=a.Gf&&d;d||(F6(a),G6(a))},vEa=function(a,b){var c=a.Tn,d=b.indexOf("\n",c);
if(-1==d)return C6;c=Number(b.substring(c,d));if(isNaN(c))return wEa;d+=1;if(d+c>b.length)return C6;var e=b.substr(d,c);a.Tn=d+c;return e},zEa=function(a,b){a.Tk=(0,g.H)();
B6(a);var c=b?window.location.hostname:"";a.di=a.Ch.clone();g.En(a.di,"DOMAIN",c);g.En(a.di,"t",a.F);try{a.If=new ActiveXObject("htmlfile")}catch(n){F6(a);a.Dh=7;D6(22);G6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in H6)k=H6[l];else if(l in yEa)k=H6[l]=yEa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
H6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Fd(g.Tc("b/12014412"),d+"</body></html>");a.If.open();a.If.write(g.td(c));a.If.close();a.If.parentWindow.m=(0,g.A)(a.oU,a);a.If.parentWindow.d=(0,g.A)(a.QE,a,!0);a.If.parentWindow.rpcClose=(0,g.A)(a.QE,a,!1);c=a.If.createElement("DIV");a.If.parentWindow.document.body.appendChild(c);d=g.gd(a.di.toString());d=g.rc(g.dd(d));d=g.Fd(g.Tc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Bd(c,g.td(d));a.o.Af(1)},B6=function(a){a.iy=(0,g.H)()+
a.C;
AEa(a,a.C)},AEa=function(a,b){if(null!=a.vl)throw Error("WatchDog timer not null");
a.vl=I6((0,g.A)(a.DU,a),b)},J6=function(a){a.vl&&(g.v.clearTimeout(a.vl),a.vl=null)},G6=function(a){a.o.zB()||a.ri||a.o.Cq(a)},F6=function(a){J6(a);
g.Bf(a.Tq);a.Tq=null;a.A.stop();g.Rn(a.Y);if(a.Vc){var b=a.Vc;a.Vc=null;b.abort();b.dispose()}a.If&&(a.If=null)},E6=function(a,b){try{a.o.JE(a,b),a.o.Af(4)}catch(c){}},CEa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;BEa(a,b,function(e){e?c(!0):g.v.setTimeout(function(){CEa(a,b,c,d,f)},f)})}},BEa=function(a,b,c){var d=new Image;
d.onload=function(){try{K6(d),c(!0)}catch(e){}};
d.onerror=function(){try{K6(d),c(!1)}catch(e){}};
d.onabort=function(){try{K6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{K6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},K6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},DEa=function(a){this.o=a;
this.A=new y6},EEa=function(a){var b=L6(a.o,a.Ll,"/mail/images/cleardot.gif");
c6(b);CEa(b.toString(),5E3,(0,g.A)(a.dK,a),3,2E3);a.Af(1)},N6=function(a){var b=a.o.J;
if(null!=b)D6(5),b?(D6(11),M6(a.o,a,!1)):(D6(12),M6(a.o,a,!0));else if(a.Ee=new z6(a,void 0,void 0,void 0),a.Ee.Ji=a.ru,b=a.o,b=L6(b,b.Ln()?a.Cm:null,a.tu),D6(5),!g.ae||g.Lc(10))d6(b,"TYPE","xmlhttp"),A6(a.Ee,b,!1,a.Cm,!1);else{d6(b,"TYPE","html");var c=a.Ee;a=!!a.Cm;c.Xj=3;c.Ch=c6(b.clone());zEa(c,a)}},O6=function(a,b,c){this.o=1;
this.A=[];this.C=[];this.D=new y6;this.H=a||null;this.J=null!=b?b:null;this.F=c||!1},FEa=function(a,b){this.o=a;
this.map=b;this.context=null},GEa=function(a){g.Df.call(this,"statevent",a)},HEa=function(a,b){g.Df.call(this,"timingevent",a);
this.size=b},IEa=function(a){g.Df.call(this,"serverreachability",a)},LEa=function(a){JEa(a);
if(3==a.o){var b=a.tn++,c=a.ep.clone();g.En(c,"SID",a.B);g.En(c,"RID",b);g.En(c,"TYPE","terminate");P6(a,c);b=new z6(a,a.B,b,void 0);b.Xj=2;b.Ch=c6(c.clone());(new Image).src=b.Ch;b.Tk=(0,g.H)();B6(b)}KEa(a)},MEa=function(a){a.AK(1,0);
a.ep=L6(a,null,a.qu);Q6(a)},JEa=function(a){a.qh&&(a.qh.abort(),a.qh=null);
a.Ac&&(a.Ac.cancel(),a.Ac=null);a.Gg&&(g.v.clearTimeout(a.Gg),a.Gg=null);R6(a);a.ie&&(a.ie.cancel(),a.ie=null);a.wh&&(g.v.clearTimeout(a.wh),a.wh=null)},NEa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new FEa(a.bQ++,b));2!=a.o&&3!=a.o||Q6(a)},Q6=function(a){a.ie||a.wh||(a.wh=I6((0,g.A)(a.PE,a),0),a.Oj=0)},PEa=function(a,b){if(1==a.o){if(!b){a.tn=Math.floor(1E5*Math.random());
var c=a.tn++,d=new z6(a,"",c,void 0);d.Ji=null;var e=S6(a),f=a.ep.clone();g.En(f,"RID",c);g.En(f,"CVER","1");P6(a,f);uEa(d,f,e);a.ie=d;a.o=2}}else 3==a.o&&(b?OEa(a,b):0==a.A.length||a.ie||OEa(a))},OEa=function(a,b){if(b)if(6<a.wi){a.A=a.C.concat(a.A);
a.C.length=0;var c=a.tn-1;var d=S6(a)}else c=b.G,d=b.jj;else c=a.tn++,d=S6(a);var e=a.ep.clone();g.En(e,"SID",a.B);g.En(e,"RID",c);g.En(e,"AID",a.tk);P6(a,e);c=new z6(a,a.B,c,a.Oj+1);c.Ji=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ie=c;uEa(c,e,d)},P6=function(a,b){if(a.Ed){var c=a.Ed.eB();
c&&g.Kb(c,function(a,c){g.En(b,c,a)})}},S6=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.wi&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.wi?e:f-d;try{g.Kb(k,function(a,b){c.push("req"+f+"_"+b+"="+encodeURIComponent(a))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.C=a.C.concat(a.A.splice(0,b));
return c.join("&")},QEa=function(a){a.Ac||a.Gg||(a.G=1,a.Gg=I6((0,g.A)(a.OE,a),0),a.Fj=0)},T6=function(a){if(a.Ac||a.Gg||3<=a.Fj)return!1;
a.G++;a.Gg=I6((0,g.A)(a.OE,a),REa(a,a.Fj));a.Fj++;return!0},M6=function(a,b,c){a.Pr=c;
a.Uf=b.Tg;a.F||MEa(a)},R6=function(a){null!=a.yi&&(g.v.clearTimeout(a.yi),a.yi=null)},REa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},U6=function(a,b){if(2==b||9==b){var c=null;
a.Ed&&(c=null);var d=(0,g.A)(a.bW,a);c||(c=new g.vn("//www.google.com/images/cleardot.gif"),c6(c));BEa(c.toString(),1E4,d)}else D6(2);SEa(a,b)},SEa=function(a,b){a.o=0;
a.Ed&&a.Ed.cA(b);KEa(a);JEa(a)},KEa=function(a){a.o=0;
a.Uf=-1;if(a.Ed)if(0==a.C.length&&0==a.A.length)a.Ed.xt();else{g.db(a.C);var b=g.db(a.A);a.C.length=0;a.A.length=0;a.Ed.xt(b)}},L6=function(a,b,c){var d=g.Fn(c);
if(""!=d.A)b&&g.xn(d,b+"."+d.A),g.yn(d,d.D);else{var e=window.location;d=XDa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.dm&&g.Kb(a.dm,function(a,b){g.En(d,b,a)});
g.En(d,"VER",a.wi);P6(a,d);return d},I6=function(a,b){if(!g.Ha(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},D6=function(a){V6.dispatchEvent(new GEa(V6,a))},TEa=function(){},UEa=function(a,b){this.action=a;
this.params=b||{}},W6=function(a,b){g.J.call(this);
this.o=new g.U(this.eU,0,this);g.K(this,this.o);this.Fd=5E3;this.A=0;if(g.Ha(a))b&&(a=(0,g.A)(a,b));else if(a&&g.Ha(a.handleEvent))a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},X6=function(a,b,c){this.K=a;
this.F=b;this.B=new g.YD;this.A=new W6(this.FW,this);this.o=this.kb=null;this.Cb=!1;this.D=null;this.J="";this.H=this.C=0;this.G=[];this.L=c||!1},VEa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Pr,sessionId:a.o.B,arrayId:a.o.tk}},WEa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&PEa(a.o),LEa(a.o));a.H=0},Y6=function(a){return!!a.o&&3==a.o.o},XEa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},Z6=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||document.location.href;var b=g.dh(a)||"";b&&(this.port=":"+b);this.domain=g.ch(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Hb(a,"10.0")&&(this.A=!1))},$6=function(a,b){var c=a.o;
if(g.za(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.mh(c+b,{})},a7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.La(a.C,d,!0),onError:g.La(a.B,e),Jd:g.La(a.D,e)};c&&(a.Sb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.DF(b,a)},aFa=function(){var a=YEa;
ZEa();b7.push(a);$Ea(b7)},c7=function(a,b){ZEa();
var c=b7,d=bFa(a,String(b));g.Wa(c)?cFa(d):($Ea(c),(0,g.C)(c,function(a){a(d)}))},ZEa=function(){b7||(b7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ca("yt.mdx.remote.debug.handlers_",b7,void 0))},cFa=function(a){var b=(d7+1)%50;
d7=b;e7[b]=a;f7||(f7=49==b)},$Ea=function(a){var b=e7;
if(b[0]){var c=d7,d=f7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
e7=Array(50);d7=-1;f7=!1}},bFa=function(a,b){var c=((0,g.H)()-dFa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},g7=function(a){g.V.call(this);
this.G=a;this.o=[]},eFa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},fFa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.oe)(a.o,function(a){return!!l6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=eFa(a,b[d])||c;return c},gFa=function(a,b){var c=a.o.length;
a.o=(0,g.oe)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},h7=function(a,b,c,d){g.V.call(this);
this.F=a;this.D=b;this.B=c;this.C=d;this.A=0;this.o=null;this.Ia=NaN},j7=function(a){g7.call(this,"LocalScreenService");
this.B=a;this.A=NaN;i7(this);this.info("Initializing with "+j6(this.o))},hFa=function(a){if(a.o.length){var b=(0,g.I)(a.o,function(a){return a.id}),c=$6(a.B,"/pairing/get_lounge_token_batch");
a7(a.B,c,{screen_ids:b.join(",")},(0,g.A)(a.qL,a),(0,g.A)(a.pL,a))}},i7=function(a){var b=cEa(iEa());
b=(0,g.oe)(b,function(a){return!a.uuid});
return fFa(a,b)},k7=function(a,b){kEa((0,g.I)(a.o,aEa));
b&&jEa()},m7=function(a,b){g.V.call(this);
this.F=b;var c=g.jI("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Va(c,l)}this.o=d;this.D=a;this.B=this.C=NaN;this.A=null;l7("Initialized with "+g.Vg(this.o))},iFa=function(a,b,c){var d=$6(a.D,"/pairing/get_screen_availability");
a7(a.D,d,{lounge_token:b.token},(0,g.A)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},n7=function(a,b){a:if(g.Qb(b)!=g.Qb(a.o))var c=!1;
else{c=g.Tb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(l7("Updated online screens: "+g.Vg(a.o)),a.o=b,a.V("screenChange"));jFa(a)},o7=function(a){isNaN(a.B)||g.UE(a.B);
a.B=g.SE((0,g.A)(a.bx,a),0<a.C&&a.C<(0,g.H)()?2E4:1E4)},l7=function(a){c7("OnlineScreenService",a)},kFa=function(a){var b={};
(0,g.C)(a.F(),function(a){a.token?b[a.token]=a.id:this.tc("Requesting availability of screen w/o lounge token.")});
return b},jFa=function(a){a=g.Tb(g.Lb(a.o,function(a){return a}));
g.qb(a);a.length?g.iI("yt-remote-online-screen-ids",a.join(","),60):g.kI("yt-remote-online-screen-ids")},p7=function(a){g7.call(this,"ScreenService");
this.F=a;this.A=this.B=null;this.C=[];this.D={};lFa(this)},nFa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.ye();if(k=(c?m6(k,c):null)||m6(k,b)){k.uuid=b;var l=q7(a,k);iFa(a.A,l,function(a){e(a?l:null)})}else c?mFa(a,c,(0,g.A)(function(a){var f=q7(this,new g6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));iFa(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},oFa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},mFa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Sb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.DF($6(a.F,"/pairing/get_lounge_token_batch"),e)},pFa=function(a){a.o=a.B.ye();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+j6(a.o))},lFa=function(a){r7(a);
a.B=new j7(a.F);a.B.subscribe("screenChange",(0,g.A)(a.DL,a));pFa(a);a.C=cEa(g.jI("yt-remote-automatic-screen-cache")||[]);r7(a);a.info("Initializing automatic screens: "+j6(a.C));a.A=new m7(a.F,(0,g.A)(a.ye,a,!0));a.A.subscribe("screenChange",(0,g.A)(function(){this.V("onlineScreenChange")},a))},q7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=m6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.iI("yt-remote-automatic-screen-cache",(0,g.I)(a.C,aEa)));r7(a);a.D[b.uuid]=b.id;g.iI("yt-remote-device-id-map",a.D,31536E3);return b},r7=function(a){a.D=g.jI("yt-remote-device-id-map")||{}},s7=function(a,b,c){g.V.call(this);
this.R=c;this.J=a;this.A=b;this.B=null},t7=function(a,b){c7(a.R,b)},u7=function(a,b){s7.call(this,a,b,"CastSession");
this.o=null;this.C=0;this.F=(0,g.A)(this.LW,this);this.D=(0,g.A)(this.PU,this);this.C=g.SE((0,g.A)(function(){qFa(this,null)},this),12E4)},rFa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Vg(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.z,(0,g.A)(function(){t7(this,"Failed to send message: getMdxSessionStatus.")},a)):t7(a,"Sending yt message without session: "+g.Vg(b))},qFa=function(a,b){g.UE(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.B||a.B.id!=b){var c=(0,g.A)(a.Dq,a),d=(0,g.A)(a.De,a);a.pB(b,c,d,5)}}else a.De(Error("Waiting for session status timed out."))},v7=function(a,b,c){s7.call(this,a,b,"DialSession");
this.C=this.H=null;this.K="";this.N=c;this.D=null;this.G=g.z;this.F=NaN;this.L=(0,g.A)(this.OW,this);this.o=g.z},sFa=function(a){a.o=a.J.bH(a.K,a.A.label,a.A.friendlyName,(0,g.A)(function(a){this.o=g.z;
this.Dq(a)},a),(0,g.A)(function(a){this.o=g.z;
this.De(a)},a))},tFa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.N;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}mEa()&&(b.env_useStageMdx=1);return g.kh(b)},w7=function(a,b){s7.call(this,a,b,"ManualSession");
this.o=g.SE((0,g.A)(this.vk,this,null),150)},x7=function(a,b,c,d){g.V.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.B=[];this.C=(0,g.A)(this.nT,this)},uFa=function(a,b){return b?g.Ra(a.B,function(a){return h6(b,a.label)},a):null},y7=function(a){c7("Controller",a)},YEa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},z7=function(a){return a.D||!!a.B.length||!!a.o},A7=function(a,b,c){b!=a.o&&(g.Bf(a.o),(a.o=b)?(c?a.V("yt-remote-cast2-receiver-resumed",b.A):a.V("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.A)(a.ME,a,b)),b.B?a.V("yt-remote-cast2-session-change",b.B):c&&a.o.vk(null)):a.V("yt-remote-cast2-session-change",null))},vFa=function(a){var b=a.A.aH(),c=a.o&&a.o.A;
a=(0,g.I)(b,function(a){c&&h6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=uFa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new chrome.cast.Receiver(b,a.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},BFa=function(a,b,c,d,e,f,k){wFa()?xFa(b,e,f,k)&&(C7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?yFa(a,c):(window.__onGCastApiAvailable=function(b,d){b?yFa(a,c):(D7("Failed to load cast API: "+d),E7(!1),C7(!1),g.kI("yt-remote-cast-available"),g.kI("yt-remote-cast-receiver"),zFa(),c(!1))},d?g.eF("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?sEa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?v6():(rEa(),u6(AFa.map(pEa))))):B7("Cannot initialize because not running Chrome")},zFa=function(){B7("dispose");
var a=F7();a&&a.dispose();g.Ca("yt.mdx.remote.cloudview.instance_",null,void 0);CFa(!1);g.$E(G7);G7.length=0},H7=function(){return!!g.jI("yt-remote-cast-installed")},DFa=function(){var a=g.jI("yt-remote-cast-receiver");
return a?a.friendlyName:null},EFa=function(){B7("clearCurrentReceiver");
g.kI("yt-remote-cast-receiver")},FFa=function(){return H7()?F7()?F7().getCastSession():(D7("getCastSelector: Cast is not initialized."),null):(D7("getCastSelector: Cast API is not installed!"),null)},J7=function(){H7()?F7()?I7()?(B7("Requesting cast selector."),F7().requestSession()):(B7("Wait for cast API to be ready to request the session."),G7.push(g.ZE("yt-remote-cast2-api-ready",J7))):D7("requestCastSelector: Cast is not initialized."):D7("requestCastSelector: Cast API is not installed!")},K7=
function(a,b){I7()?F7().setConnectedScreenStatus(a,b):D7("setConnectedScreenStatus called before ready.")},wFa=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.HL||a},GFa=function(a,b){F7().init(a,b)},xFa=function(a,b,c,d){var e=!1;
F7()||(a=new x7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.iI("yt-remote-cast-available",a);e6("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){B7("onReceiverSelected: "+a.friendlyName);
g.iI("yt-remote-cast-receiver",a);e6("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){B7("onReceiverResumed: "+a.friendlyName);
g.iI("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){B7("onSessionChange: "+i6(a));
a||g.kI("yt-remote-cast-receiver");e6("yt-remote-cast2-session-change",a)}),g.Ca("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
B7("cloudview.createSingleton_: "+e);return e},F7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},yFa=function(a,b){E7(!0);
C7(!1);GFa(a,function(a){a?(CFa(!0),g.bF("yt-remote-cast2-api-ready")):(D7("Failed to initialize cast API."),E7(!1),g.kI("yt-remote-cast-available"),g.kI("yt-remote-cast-receiver"),zFa());b(a)})},B7=function(a){c7("cloudview",a)},D7=function(a){c7("cloudview",a)},E7=function(a){B7("setCastInstalled_ "+a);
g.iI("yt-remote-cast-installed",a)},I7=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},CFa=function(a){B7("setApiReady_ "+a);
g.Ca("yt.mdx.remote.cloudview.apiReady_",a,void 0)},C7=function(a){g.Ca("yt.mdx.remote.cloudview.initializing_",a,void 0)},L7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.Yf=!1;this.J=this.H=this.A=this.C=0;this.B=NaN;this.D=!1;this.reset(a)},M7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.Yf=!1;a.hasNext=!1;a.G=0;a.F=(0,g.H)();a.C=0;a.A=0;a.H=0;a.J=0;a.B=NaN;a.D=!1},N7=function(a){return a.tb()?((0,g.H)()-a.F)/1E3:0},O7=function(a,b){a.G=b;
a.F=(0,g.H)()},P7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.H)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},Q7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&M7(a)},R7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.hc(a.o);b.hasPrevious=a.Yf;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.A;b.duration=a.H;b.loadedTime=a.J;b.liveIngestionTime=a.B;return b},T7=function(a,b){g.V.call(this);
this.o=0;this.C=a;this.F=[];this.D=new g.oD;this.B=this.A=null;this.J=(0,g.A)(this.MQ,this);this.G=(0,g.A)(this.wn,this);this.H=(0,g.A)(this.LQ,this);this.K=(0,g.A)(this.YQ,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.ty,this),HFa(this))):c=3;0!=c&&(b?this.ty(c):g.SE((0,g.A)(function(){this.ty(c)},this),0));
var d=FFa();d&&S7(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},U7=function(a){return new L7(a.C.getPlayerContextData())},HFa=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.C.subscribe(a,g.La(this.iT,a),this))},a)},IFa=function(a){(0,g.C)(a.F,function(a){this.C.unsubscribeByKey(a)},a);
a.F.length=0},V7=function(a,b){50>a.D.Kc()&&g.qD(a.D,b)},X7=function(a,b,c){var d=U7(a);
O7(d,c);-1E3!=d.playerState&&(d.playerState=b);W7(a,d)},Y7=function(a,b,c){a.C.sendMessage(b,c)},W7=function(a,b){IFa(a);
a.C.setPlayerContextData(R7(b));HFa(a)},S7=function(a,b){a.B&&(a.B.removeUpdateListener(a.J),a.B.removeMediaListener(a.G),a.wn(null));
a.B=b;a.B&&(c7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.J),a.B.addMediaListener(a.G),a.B.media.length&&a.wn(a.B.media[0]))},JFa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=U7(a);b.contentId!=d.videoId&&c7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;O7(d,a.A.getEstimatedTime());W7(a,d)}else c7("CP","No cast media video. Ignoring state update.")},Z7=function(a,b,c){return(0,g.A)(function(a){this.tc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.tc("Retrying "+b+" using MDx browser channel."),Y7(this,b,c))},a)},$7=function(a,b,c){g.V.call(this);
this.D=NaN;this.N=!1;this.K=this.J=this.L=this.R=NaN;this.T=[];this.C=this.G=this.B=this.qb=this.o=null;this.sa=a;this.T.push(g.FG(window,"beforeunload",(0,g.A)(this.gL,this)));this.A=[];this.qb=new L7;this.aa=b.id;this.o=KFa(this,c);this.o.subscribe("handlerOpened",this.QQ,this);this.o.subscribe("handlerClosed",this.NQ,this);this.o.subscribe("handlerError",this.OQ,this);this.o.subscribe("handlerMessage",this.PQ,this);XEa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=this.qb.videoId;
g.lI()&&g.iI("yt-remote-session-video-id",a)},this)},a8=function(a){c7("conn",a)},KFa=function(a,b){return new X6($6(a.sa,"/bc"),b)},b8=function(a,b){a.V("proxyStateChange",b)},LFa=function(a){a.D=g.SE((0,g.A)(function(){a8("Connecting timeout");
this.F(1)},a),2E4)},c8=function(a){g.UE(a.D);
a.D=NaN},d8=function(a){g.UE(a.R);
a.R=NaN},MFa=function(a){e8(a);
a.L=g.SE((0,g.A)(function(){f8(this,"getNowPlaying")},a),2E4)},e8=function(a){g.UE(a.L);
a.L=NaN},OFa=function(a,b){b&&(c8(a),d8(a));
b==(Y6(a.o)&&isNaN(a.D))?b&&(b8(a,1),f8(a,"getSubtitlesTrack")):b?(a.Z()&&a.qb.reset(),b8(a,1),f8(a,"getNowPlaying"),NFa(a)):a.F(1)},PFa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.qb.videoId&&(g.bc(b.params)?a.qb.o=null:a.qb.o=b.params,a.V("remotePlayerChange"))},QFa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.qb.listId=b.params.listId||a.qb.listId;Q7(a.qb,c,d);a.V("remoteQueueChange")},SFa=function(a,b){b.params=b.params||{};
QFa(a,b);RFa(a,b);a.V("autoplayDismissed")},RFa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
O7(a.qb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.qb.playerState&&(c=-1E3);a.qb.playerState=c;c=Number(b.params.loadedTime);a.qb.J=isNaN(c)?0:c;c=Number(b.params.duration);a.qb.H=isNaN(c)?0:c;c=a.qb;var d=Number(b.params.liveIngestionTime);c.B=d;c.D=isNaN(d)?!1:!0;c=a.qb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.A=isNaN(e)?0:e;1==a.qb.playerState?MFa(a):e8(a);a.V("remotePlayerChange")},TFa=function(a,b){if(-1E3!=
a.qb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.qb.playerState=c;c=parseInt(b.params.currentTime,10);O7(a.qb,isNaN(c)?0:c);a.V("remotePlayerChange")}},UFa=function(a,b){var c="true"==b.params.muted;
a.qb.volume=parseInt(b.params.volume,10);a.qb.muted=c;a.V("remotePlayerChange")},VFa=function(a,b){a.G=b.params.videoId;
a.V("nowAutoplaying",parseInt(b.params.timeout,10))},WFa=function(a,b){var c="true"==b.params.hasNext;
a.qb.Yf="true"==b.params.hasPrevious;a.qb.hasNext=c;a.V("previousNextChange")},NFa=function(a){g.UE(a.K);
a.K=g.SE((0,g.A)(a.F,a,1),864E5)},f8=function(a,b,c){c?a8("Sending: action="+b+", params="+g.Vg(c)):a8("Sending: action="+b);
a.o.sendMessage(b,c)},g8=function(a){g7.call(this,"ScreenServiceProxy");
this.ld=a;this.A=[];this.A.push(this.ld.$_s("screenChange",(0,g.A)(this.JW,this)));this.A.push(this.ld.$_s("onlineScreenChange",(0,g.A)(this.HS,this)))},aGa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.KE("MDX_CONFIG")||b;eEa();q6();h8||(h8=new Z6(b?b.loungeApiHost:void 0),mEa()&&(h8.o="/api/loungedev"));i8||(i8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ca("yt.mdx.remote.deferredProxies_",i8,void 0));XFa();var c=j8();if(!c){var d=new p7(h8);g.Ca("yt.mdx.remote.screenService_",d,void 0);c=j8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);BFa(a,d,function(a){a?k8()&&K7(k8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){e6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ca("yt.mdx.remote.initialized_",!0,void 0),l8("Initializing: "+g.Vg(b)),m8.push(g.ZE("yt-remote-cast2-availability-change",function(){e6("yt-remote-receiver-availability-change")})),m8.push(g.ZE("yt-remote-cast2-receiver-selected",function(){n8(null);
e6("yt-remote-auto-connect","cast-selector-receiver")})),m8.push(g.ZE("yt-remote-cast2-receiver-resumed",function(){e6("yt-remote-receiver-resumed","cast-selector-receiver")})),m8.push(g.ZE("yt-remote-cast2-session-change",YFa)),m8.push(g.ZE("yt-remote-connection-change",function(a){a?K7(k8(),"YouTube TV"):o8()||(K7(null,null),EFa())})),a=p8(),b.isAuto&&(a.id+="#dial"),g.mF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),l8(" -- with channel params: "+
g.Vg(a)),ZFa(a),c.start(),k8()||$Fa())},cGa=function(){var a=bGa();
H7()&&g.jI("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},bGa=function(){var a=j8().ld.$_gos();
var b=q8();b&&r8()&&(l6(a,b)||a.push(b));return dEa(a)},s8=function(){var a=dGa();
!a&&H7()&&DFa()&&(a={key:"cast-selector-receiver",name:DFa()});return a},dGa=function(){var a=bGa(),b=q8();
b||(b=o8());return g.Ra(a,function(a){return b&&h6(b,a.key)?!0:!1})},q8=function(){var a=k8();
if(!a)return null;var b=j8().ye();return m6(b,a)},YFa=function(a){l8("remote.onCastSessionChange_: "+i6(a));
if(a){var b=q8();b&&b.id==a.id?K7(b.id,"YouTube TV"):(b&&t8(),u8(a,1))}else r8()&&t8()},t8=function(){I7()?F7().stopSession():D7("stopSession called before API ready.");
var a=r8();a&&(a.disconnect(1),v8(null))},w8=function(){var a=r8();
return!!a&&3!=a.getProxyState()},l8=function(a){c7("remote",a)},j8=function(){if(!x8){var a=g.w("yt.mdx.remote.screenService_");
x8=a?new g8(a):null}return x8},k8=function(){return g.w("yt.mdx.remote.currentScreenId_")},eGa=function(a){g.Ca("yt.mdx.remote.currentScreenId_",a,void 0)},fGa=function(){return g.w("yt.mdx.remote.connectData_")},n8=function(a){g.Ca("yt.mdx.remote.connectData_",a,void 0)},r8=function(){return g.w("yt.mdx.remote.connection_")},v8=function(a){var b=r8();
n8(null);a||eGa("");g.Ca("yt.mdx.remote.connection_",a,void 0);i8&&((0,g.C)(i8,function(b){b(a)}),i8.length=0);
b&&!a?e6("yt-remote-connection-change",!1):!b&&a&&e6("yt-remote-connection-change",!0)},o8=function(){var a=g.lI();
if(!a)return null;var b=j8().ye();return m6(b,a)},u8=function(a,b){q8()&&q8();
eGa(a.id);var c=new $7(h8,a,p8());c.connect(b,fGa());c.subscribe("beforeDisconnect",function(a){e6("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){r8()&&v8(null)});
v8(c)},$Fa=function(){var a=o8();
a?(l8("Resume connection to: "+i6(a)),u8(a,0)):(r6(),EFa(),l8("Skipping connecting because no session screen found."))},XFa=function(){var a=p8();
if(g.bc(a)){a=p6();var b=g.jI("yt-remote-session-name")||"",c=g.jI("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ca("yt.mdx.remote.channelParams_",a,void 0)}},p8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},ZFa=function(a){a?(g.iI("yt-remote-session-app",a.app),g.iI("yt-remote-session-name",a.name)):(g.kI("yt-remote-session-app"),g.kI("yt-remote-session-name"));
g.Ca("yt.mdx.remote.channelParams_",a,void 0)},y8=function(a,b,c){g.J.call(this);
this.D=a;this.A=b;this.B=new g.UG(this);g.K(this,this.B);this.B.O(b,"onCaptionsTrackListChanged",this.bS);this.B.O(b,"captionschanged",this.KQ);this.B.O(b,"captionssettingschanged",this.nG);this.B.O(b,"videoplayerreset",this.Eq);this.B.O(b,"mdxautoplaycancel",this.cK);this.T=this.B.O(b,"onVolumeChange",this.tE);this.H=!1;this.o=c;c.subscribe("proxyStateChange",this.IE,this);c.subscribe("remotePlayerChange",this.zn,this);c.subscribe("remoteQueueChange",this.Eq,this);c.subscribe("autoplayUpNext",this.fE,
this);c.subscribe("previousNextChange",this.FE,this);c.subscribe("nowAutoplaying",this.xE,this);c.subscribe("autoplayDismissed",this.eE,this);this.suggestion=null;this.J=new g.MQ(64);this.C=new g.U(this.kG,500,this);g.K(this,this.C);this.F=new g.U(this.lG,1E3,this);g.K(this,this.F);this.L=new x6(this.lW,0,this);g.K(this,this.L);this.G={};this.R=new g.U(this.NG,1E3,this);g.K(this,this.R);this.K=new g.Yl(this.EO,1E3,this);g.K(this,this.K);this.N=g.z;this.nG();this.Eq();this.zn()},z8=function(a,b){a.D.Ie(b,
a.A.getVideoData().lengthSeconds)},gGa=function(a){z8(a,0);
a.C.stop();A8(a,new g.MQ(64))},C8=function(a,b){if(B8(a)&&!a.H){var c=null;
b&&(c={style:a.A.getSubtitlesUserSettings()},g.jc(c,b));a.o.XF(a.A.getVideoData(1).videoId,c);a.G=U7(a.o).o}},D8=function(a,b){var c=a.A.getPlaylist();
if(c){var d=c.xe();var e=c.listId.toString()}c=a.A.getVideoData(1);a.o.playVideo(c.videoId,b,d,e,c.playerParams,c.ik,WDa(c));A8(a,new g.MQ(1))},hGa=function(a,b){if(b){var c=a.A.getOption("captions","tracklist",{K4:1});
c&&c.length?(a.A.setOption("captions","track",b),a.H=!1):(a.A.loadModule("captions"),a.H=!0)}else a.A.setOption("captions","track",{})},B8=function(a){return U7(a.o).videoId==a.A.getVideoData(1).videoId},A8=function(a,b){a.F.stop();
var c=a.J;if(!g.SQ(c,b)){var d=g.X(b,2);d!=g.X(a.J,2)&&g.VU(a.A,d);a.J=b;iGa(a.D,c,b)}},E8=function(a){g.W.call(this,{I:"div",
M:"ytp-remote",P:[{I:"div",M:"ytp-remote-display-status",P:[{I:"div",M:"ytp-remote-display-status-icon",P:[g.zsa()]},{I:"div",M:"ytp-remote-display-status-text",ba:"{{statustext}}"}]}]});this.B=new g.MV(this,250);g.K(this,this.B);this.C=a;this.O(a,"presentingplayerstatechange",this.D);jGa(this,g.RU(a))},jGa=function(a,b){if(3==a.C.getPresentingPlayerType()){var c={RECEIVER_NAME:a.C.getOption("remote","currentReceiver").name};
c=g.X(b,128)?g.EV("Error on $RECEIVER_NAME",c):b.tb()||g.X(b,4)?g.EV("Playing on $RECEIVER_NAME",c):g.EV("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.B.show()}else a.B.hide()},F8=function(a,b){g.cX.call(this,"Play on",0,a,b);
this.B=a;this.H={};this.O(a,"onMdxReceiversChange",this.L);this.O(a,"presentingplayerstatechange",this.L);this.L()},G8=function(a){g.oV.call(this,a);
this.A={key:k6(),name:"This computer"};this.C=null;this.D=[];this.G=this.o=null;this.F=[this.A];this.B=this.A;this.gn=new g.MQ(64);this.J=0;this.H=-1;if(!g.GN(g.Y(this.player))){a=this.player;var b=g.BQ(a);b&&(b=b.jn())&&(b=new F8(a,b),g.K(this,b));b=new E8(a);g.K(this,b);g.fV(a,b.element,4)}},iGa=function(a,b,c){a.gn=c;
a.player.V("presentingplayerstatechange",new g.WQ(c,b))},H8=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)t8();
else{a.B=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Ga(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.ik,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(d=WDa(d))&&(c.locationInfo=d);d=c}else d=null;l8("Connecting to: "+g.Vg(b));"cast-selector-receiver"==b.key?
(n8(d||null),I7()?F7().setLaunchParams(d||null):D7("setLaunchParams called before ready.")):!d&&w8()&&k8()==b.key?e6("yt-remote-connection-change",!0):(t8(),n8(d||null),d=j8().ye(),(d=m6(d,b.key))&&u8(d,1))}},yEa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},H6={"'":"\\'"},kGa={},$Da={hY:"atp",O2:"ska",c2:"que",m1:"mus",K2:"sus",v_:"dsp",u2:"seq"};
f6.prototype.rh=function(){var a=new f6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.B=this.B;a.A=this.A;a.o=this.o};
var s6,o6="",w6=t6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",qEa=t6("loadCastFramework")||t6("loadCastApplicationFramework"),AFa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.B(x6,g.J);g.h=x6.prototype;g.h.bL=function(a){this.C=arguments;this.o=!1;this.Ia?this.B=(0,g.H)()+this.Fd:this.Ia=g.Qg(this.D,this.Fd)};
g.h.stop=function(){this.Ia&&(g.Rg(this.Ia),this.Ia=null);this.B=null;this.o=!1;this.C=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.C)))};
g.h.W=function(){this.stop();x6.ga.W.call(this)};
g.h.cL=function(){this.B?(this.Ia=g.Qg(this.D,this.B-(0,g.H)()),this.B=null):(this.Ia=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.C)))};y6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};g.h=z6.prototype;g.h.Ji=null;g.h.Gf=!1;g.h.vl=null;g.h.iy=null;g.h.Tk=null;g.h.Xj=null;g.h.Ch=null;g.h.di=null;g.h.jj=null;g.h.Vc=null;g.h.Tn=0;g.h.If=null;g.h.Sr=null;g.h.Dh=null;g.h.Dm=-1;g.h.FF=!0;g.h.ri=!1;g.h.uu=0;g.h.Tq=null;var wEa={},C6={};g.h=z6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.iV=function(a){a=a.target;var b=this.Tq;b&&3==g.jy(a)?b.zm():this.XG(a)};
g.h.XG=function(a){try{if(a==this.Vc)a:{var b=g.jy(this.Vc),c=this.Vc.A,d=this.Vc.getStatus();if(g.ae&&!g.Lc(10)||g.ce&&!g.Kc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Ff&&!g.ny(this.Vc))break a;this.ri||4!=b||7==c||(8==c||0>=d?this.o.Af(3):this.o.Af(2));J6(this);var e=this.Vc.getStatus();this.Dm=e;var f=g.ny(this.Vc);(this.Gf=200==e)?(4==b&&F6(this),this.D?(xEa(this,b,f),g.Ff&&this.Gf&&3==b&&(this.Y.X(this.A,"tick",this.dV),this.A.start())):E6(this,f),this.Gf&&!this.ri&&(4==b?this.o.Cq(this):
(this.Gf=!1,B6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Dh=3,D6(13)):(this.Dh=0,D6(14)),F6(this),G6(this))}}catch(k){this.Vc&&g.ny(this.Vc)}finally{}};
g.h.dV=function(){var a=g.jy(this.Vc),b=g.ny(this.Vc);this.Tn<b.length&&(J6(this),xEa(this,a,b),this.Gf&&4!=a&&B6(this))};
g.h.oU=function(a){I6((0,g.A)(this.nU,this,a),0)};
g.h.nU=function(a){this.ri||(J6(this),E6(this,a),B6(this))};
g.h.QE=function(a){I6((0,g.A)(this.mU,this,a),0)};
g.h.mU=function(a){this.ri||(F6(this),this.Gf=a,this.o.Cq(this),this.o.Af(4))};
g.h.cancel=function(){this.ri=!0;F6(this)};
g.h.DU=function(){this.vl=null;var a=(0,g.H)();0<=a-this.iy?(2!=this.Xj&&this.o.Af(3),F6(this),this.Dh=2,D6(18),G6(this)):AEa(this,this.iy-a)};
g.h.getLastError=function(){return this.Dh};g.h=DEa.prototype;g.h.ru=null;g.h.Ee=null;g.h.Uq=!1;g.h.AB=null;g.h.bp=null;g.h.yv=null;g.h.tu=null;g.h.Ye=null;g.h.Tg=-1;g.h.Cm=null;g.h.Ll=null;g.h.connect=function(a){this.tu=a;a=L6(this.o,null,this.tu);D6(3);this.AB=(0,g.H)();var b=this.o.H;null!=b?(this.Cm=b[0],(this.Ll=b[1])?(this.Ye=1,EEa(this)):(this.Ye=2,N6(this))):(d6(a,"MODE","init"),this.Ee=new z6(this,void 0,void 0,void 0),this.Ee.Ji=this.ru,A6(this.Ee,a,!1,null,!0),this.Ye=0)};
g.h.dK=function(a){if(a)this.Ye=2,N6(this);else{D6(4);var b=this.o;b.Uf=b.qh.Tg;U6(b,9)}a&&this.Af(2)};
g.h.Mt=function(a){return this.o.Mt(a)};
g.h.abort=function(){this.Ee&&(this.Ee.cancel(),this.Ee=null);this.Tg=-1};
g.h.zB=function(){return!1};
g.h.JE=function(a,b){this.Tg=a.Dm;if(0==this.Ye)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.Uf=this.Tg;U6(c,2);return}this.Cm=c[0];this.Ll=c[1]}else c=this.o,c.Uf=this.Tg,U6(c,2);else if(2==this.Ye)if(this.Uq)D6(7),this.yv=(0,g.H)();else if("11111"==b){if(D6(6),this.Uq=!0,this.bp=(0,g.H)(),c=this.bp-this.AB,!g.ae||g.Lc(10)||500>c)this.Tg=200,this.Ee.cancel(),D6(12),M6(this.o,this,!0)}else D6(8),this.bp=this.yv=(0,g.H)(),this.Uq=!1};
g.h.Cq=function(){this.Tg=this.Ee.Dm;if(this.Ee.Gf)0==this.Ye?this.Ll?(this.Ye=1,EEa(this)):(this.Ye=2,N6(this)):2==this.Ye&&((!g.ae||g.Lc(10)?!this.Uq:200>this.yv-this.bp)?(D6(11),M6(this.o,this,!1)):(D6(12),M6(this.o,this,!0)));else{0==this.Ye?D6(9):2==this.Ye&&D6(10);var a=this.o;a.Uf=this.Tg;U6(a,2)}};
g.h.Ln=function(){return this.o.Ln()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Af=function(a){this.o.Af(a)};g.h=O6.prototype;g.h.dm=null;g.h.ie=null;g.h.Ac=null;g.h.qu=null;g.h.ep=null;g.h.Rz=null;g.h.vp=null;g.h.tn=0;g.h.bQ=0;g.h.Ed=null;g.h.wh=null;g.h.Gg=null;g.h.yi=null;g.h.qh=null;g.h.Pr=null;g.h.tk=-1;g.h.rC=-1;g.h.Uf=-1;g.h.Oj=0;g.h.Fj=0;g.h.wi=8;var V6=new g.eg;g.B(GEa,g.Df);g.B(HEa,g.Df);g.B(IEa,g.Df);g.h=O6.prototype;g.h.connect=function(a,b,c,d,e){D6(0);this.qu=b;this.dm=c||{};d&&g.za(e)&&(this.dm.OSID=d,this.dm.OAID=e);this.F?(I6((0,g.A)(this.kA,this,a),100),MEa(this)):this.kA(a)};
g.h.kA=function(a){this.qh=new DEa(this);this.qh.ru=null;this.qh.A=this.D;this.qh.connect(a)};
g.h.zB=function(){return 0==this.o};
g.h.PE=function(a){this.wh=null;PEa(this,a)};
g.h.OE=function(){this.Gg=null;this.Ac=new z6(this,this.B,"rpc",this.G);this.Ac.Ji=null;this.Ac.uu=0;var a=this.Rz.clone();g.En(a,"RID","rpc");g.En(a,"SID",this.B);g.En(a,"CI",this.Pr?"0":"1");g.En(a,"AID",this.tk);P6(this,a);if(!g.ae||g.Lc(10))g.En(a,"TYPE","xmlhttp"),A6(this.Ac,a,!0,this.vp,!1);else{g.En(a,"TYPE","html");var b=this.Ac,c=!!this.vp;b.Xj=3;b.Ch=c6(a.clone());zEa(b,c)}};
g.h.JE=function(a,b){if(0!=this.o&&(this.Ac==a||this.ie==a))if(this.Uf=a.Dm,this.ie==a&&3==this.o)if(7<this.wi){try{var c=this.D.parse(b)}catch(f){c=null}if(g.Fa(c)&&3==c.length)if(0==c[0])a:{if(!this.Gg){if(this.Ac)if(this.Ac.Tk+3E3<this.ie.Tk)R6(this),this.Ac.cancel(),this.Ac=null;else break a;T6(this);D6(19)}}else this.rC=c[1],0<this.rC-this.tk&&37500>c[2]&&this.Pr&&0==this.Fj&&!this.yi&&(this.yi=I6((0,g.A)(this.FQ,this),6E3));else U6(this,11)}else b!=kGa.mZ.o&&U6(this,11);else if(this.Ac==a&&
R6(this),!g.D(b)){c=this.D.parse(b);g.Fa(c);for(var d=0;d<c.length;d++){var e=c[d];this.tk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.B=e[1],this.vp=e[2],e=e[3],null!=e?this.wi=e:this.wi=6,this.o=3,this.Ed&&this.Ed.eA(),this.Rz=L6(this,this.Ln()?this.vp:null,this.qu),QEa(this)):"stop"==e[0]&&U6(this,7):3==this.o&&("stop"==e[0]?U6(this,7):"noop"!=e[0]&&this.Ed&&this.Ed.dA(e),this.Fj=0)}}};
g.h.FQ=function(){null!=this.yi&&(this.yi=null,this.Ac.cancel(),this.Ac=null,T6(this),D6(20))};
g.h.Cq=function(a){if(this.Ac==a){R6(this);this.Ac=null;var b=2}else if(this.ie==a)this.ie=null,b=1;else return;this.Uf=a.Dm;if(0!=this.o)if(a.Gf)1==b?(b=(0,g.H)()-a.Tk,V6.dispatchEvent(new HEa(V6,a.jj?a.jj.length:0,b,this.Oj)),Q6(this),this.C.length=0):QEa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Uf)){if(d=1==b)this.ie||this.wh||1==this.o||2<=this.Oj?d=!1:(this.wh=I6((0,g.A)(this.PE,this,a),REa(this,this.Oj)),this.Oj++,d=!0);d=!(d||2==b&&T6(this))}if(d)switch(c){case 1:U6(this,
5);break;case 4:U6(this,10);break;case 3:U6(this,6);break;case 7:U6(this,12);break;default:U6(this,2)}}};
g.h.AK=function(a){if(!g.Va(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.bW=function(a){a?D6(2):(D6(1),SEa(this,8))};
g.h.Mt=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.dy;a.H=!1;return a};
g.h.isActive=function(){return!!this.Ed&&this.Ed.isActive(this)};
g.h.Af=function(a){V6.dispatchEvent(new IEa(V6,a))};
g.h.Ln=function(){return!(!g.ae||g.Lc(10))};
g.h=TEa.prototype;g.h.eA=function(){};
g.h.dA=function(){};
g.h.cA=function(){};
g.h.xt=function(){};
g.h.eB=function(){return{}};
g.h.isActive=function(){return!0};g.B(W6,g.J);g.h=W6.prototype;g.h.eU=function(){this.Fd=Math.min(3E5,2*this.Fd);this.B();this.A&&this.start()};
g.h.start=function(){var a=this.Fd+15E3*Math.random();g.cv(this.o,a);this.A=(0,g.H)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Fd=5E3};g.B(X6,TEa);g.h=X6.prototype;g.h.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.h.zk=function(a){return this.B.Ki(a)};
g.h.V=function(a,b){return this.B.V.apply(this.B,arguments)};
g.h.dispose=function(){this.Cb||(this.Cb=!0,g.Bf(this.B),WEa(this),g.Bf(this.A),this.A=null)};
g.h.la=function(){return this.Cb};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.A.stop();this.D=a||null;this.C=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new O6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.L),e=this.o;e&&(e.Ed=null);d.Ed=this;this.o=d;e?this.o.connect(a,b,this.F,e.B,e.tk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.jc(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):Y6(this)&&NEa(this.o,c)};
g.h.eA=function(){this.A.reset();this.D=null;this.C=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)NEa(this.o,a[b])}this.V("handlerOpened")};
g.h.cA=function(a){var b=2==a&&401==this.o.Uf;4==a||b||this.A.start();this.V("handlerError",a)};
g.h.xt=function(a){if(!this.A.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.eB=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.C&&(a.ui=""+this.C);0!=this.H&&(a.ui=""+this.H);this.D&&g.jc(a,this.D);return a};
g.h.dA=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),LEa(this.o)):this.V("handlerMessage",new UEa(a[0],a[1]))};
g.h.FW=function(){this.A.isActive();var a=this.o,b=0;a.Ac&&b++;a.ie&&b++;0!=b||this.connect(this.D,this.C)};Z6.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
Z6.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
Z6.prototype.D=function(a){a(Error("request timed out"))};var dFa=(0,g.H)(),b7=null,e7=Array(50),d7=-1,f7=!1;g.B(g7,g.V);g7.prototype.ye=function(){return this.o};
g7.prototype.contains=function(a){return!!l6(this.o,a)};
g7.prototype.get=function(a){return a?m6(this.o,a):null};
g7.prototype.info=function(a){c7(this.G,a)};g.B(h7,g.V);var lGa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=h7.prototype;g.h.start=function(){!this.o&&isNaN(this.Ia)&&this.ZG()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ia)||(g.UE(this.Ia),this.Ia=NaN)};
g.h.W=function(){this.stop();h7.ga.W.call(this)};
g.h.ZG=function(){this.Ia=NaN;this.o=g.DF($6(this.F,"/pairing/get_screen"),{method:"POST",Sb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.A)(this.HW,this),onError:(0,g.A)(this.GW,this),Jd:(0,g.A)(this.IW,this)})};
g.h.HW=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.V("pairingComplete",new g6(c))};
g.h.GW=function(a){this.o=null;a.status&&404==a.status?this.A>=lGa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=lGa[this.A],this.Ia=g.SE((0,g.A)(this.ZG,this),a),this.A++):this.V("pairingFailed",Error("Server error "+a.status))};
g.h.IW=function(){this.o=null;this.V("pairingFailed",Error("Server not responding"))};g.B(j7,g7);g.h=j7.prototype;g.h.start=function(){i7(this)&&this.V("screenChange");!g.jI("yt-remote-lounge-token-expiration")&&hFa(this);g.UE(this.A);this.A=g.SE((0,g.A)(this.start,this),1E4)};
g.h.add=function(a,b){i7(this);eFa(this,a);k7(this,!1);this.V("screenChange");b(a);a.token||hFa(this)};
g.h.remove=function(a,b){var c=i7(this);gFa(this,a)&&(k7(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.h.Lr=function(a,b,c,d){var e=i7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,k7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.h.W=function(){g.UE(this.A);j7.ga.W.call(this)};
g.h.qL=function(a){i7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}k7(this,!b);b&&c7(this.G,"Missed "+b+" lounge tokens.")};
g.h.pL=function(a){c7(this.G,"Requesting lounge tokens failed: "+a)};g.B(m7,g.V);g.h=m7.prototype;g.h.start=function(){var a=parseInt(g.jI("yt-remote-fast-check-period")||"0",10);(this.C=(0,g.H)()-144E5<a?0:a)?o7(this):(this.C=(0,g.H)()+3E5,g.iI("yt-remote-fast-check-period",this.C),this.bx())};
g.h.isEmpty=function(){return g.bc(this.o)};
g.h.update=function(){l7("Updating availability on schedule.");var a=this.F(),b=g.Lb(this.o,function(b,d){return b&&!!m6(a,d)},this);
n7(this,b)};
g.h.W=function(){g.UE(this.B);this.B=NaN;this.A&&(this.A.abort(),this.A=null);m7.ga.W.call(this)};
g.h.bx=function(){g.UE(this.B);this.B=NaN;this.A&&this.A.abort();var a=kFa(this);if(g.Qb(a)){var b=$6(this.D,"/pairing/get_screen_availability");this.A=a7(this.D,b,{lounge_token:g.Tb(a).join(",")},(0,g.A)(this.JT,this,a),(0,g.A)(this.IT,this))}else n7(this,{}),o7(this)};
g.h.JT=function(a,b){this.A=null;var c=g.Tb(kFa(this));if(g.rb(c,g.Tb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;n7(this,d);o7(this)}else this.tc("Changing Screen set during request."),this.bx()};
g.h.IT=function(a){this.tc("Screen availability failed: "+a);this.A=null;o7(this)};
g.h.tc=function(a){c7("OnlineScreenService",a)};g.B(p7,g7);g.h=p7.prototype;g.h.start=function(){this.B.start();this.A.start();this.o.length&&(this.V("screenChange"),this.A.isEmpty()||this.V("onlineScreenChange"))};
g.h.add=function(a,b,c){this.B.add(a,b,c)};
g.h.remove=function(a,b,c){this.B.remove(a,b,c);this.A.update()};
g.h.Lr=function(a,b,c,d){this.B.contains(a)?this.B.Lr(a,b,c,d):(a="Updating name of unknown screen: "+a.name,c7(this.G,a),d(Error(a)))};
g.h.ye=function(a){return a?this.o:g.cb(this.o,(0,g.oe)(this.C,function(a){return!this.contains(a)},this))};
g.h.aH=function(){return(0,g.oe)(this.ye(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.bH=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new h7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(a){g.Bf(f);d(q7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.Bf(f);e(a)});
f.start();return(0,g.A)(f.stop,f)};
g.h.KW=function(a,b,c,d){g.DF($6(this.F,"/pairing/get_screen"),{method:"POST",Sb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.A)(function(a,d){var e=new g6(d.screen||{});if(!e.name||oFa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);oFa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(q7(this,e))},this),
onError:(0,g.A)(function(a){d(Error("pairing request failed: "+a.status))},this),
Jd:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.h.W=function(){g.Bf(this.B);g.Bf(this.A);p7.ga.W.call(this)};
g.h.DL=function(){pFa(this);this.V("screenChange");this.A.update()};
p7.prototype.dispose=p7.prototype.dispose;g.B(s7,g.V);g.h=s7.prototype;g.h.Dq=function(a){this.B=a;this.V("sessionScreen",this.B)};
g.h.De=function(a){this.la()||(a&&t7(this,""+a),this.B=null,this.V("sessionScreen",null))};
g.h.info=function(a){c7(this.R,a)};
g.h.dH=function(){return null};
g.h.tx=function(a){var b=this.A;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){t7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.W=function(){this.tx("");s7.ga.W.call(this)};g.B(u7,s7);g.h=u7.prototype;g.h.rx=function(a){if(this.o){if(this.o==a)return;t7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);rFa(this)};
g.h.vk=function(a){this.info("launchWithParams no-op for Cast: "+g.Vg(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.A)(function(){this.De()},this),(0,g.A)(function(){this.De(Error("Failed to stop receiver app."))},this)):this.De(Error("Stopping cast device witout session."))};
g.h.tx=g.z;g.h.W=function(){this.info("disposeInternal");g.UE(this.C);this.C=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;u7.ga.W.call(this)};
g.h.PU=function(a,b){if(!this.la())if(b){var c=g.Zx(b);if(g.Ia(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Vg(c));switch(d){case "mdxSessionStatus":qFa(this,c.screenId);break;default:t7(this,"Unknown youtube message: "+d)}}else t7(this,"Unable to parse message.")}else t7(this,"No data in message.")};
g.h.pB=function(a,b,c,d){nFa(this.J,this.A.label,a,this.A.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(t7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.SE((0,g.A)(this.pB,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.dH=function(){return this.o};
g.h.LW=function(a){this.la()||a||(t7(this,"Cast session died."),this.De())};g.B(v7,s7);g.h=v7.prototype;g.h.rx=function(a){this.C=a;this.C.addUpdateListener(this.L)};
g.h.vk=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.z;g.UE(this.F);this.C?this.C.stop((0,g.A)(this.De,this,null),(0,g.A)(this.De,this,"Failed to stop DIAL device.")):this.De()};
g.h.W=function(){this.o();this.o=g.z;g.UE(this.F);this.C&&this.C.removeUpdateListener(this.L);this.C=null;v7.ga.W.call(this)};
g.h.OW=function(a){this.la()||a||(t7(this,"DIAL session died."),this.o(),this.o=g.z,this.De())};
g.h.Vu=function(a){this.K=k6();if(this.D){var b=new chrome.cast.DialLaunchResponse(!0,tFa(this));a(b);sFa(this)}else this.G=(0,g.A)(function(){g.UE(this.F);this.G=g.z;this.F=NaN;var b=new chrome.cast.DialLaunchResponse(!0,tFa(this));a(b);sFa(this)},this),this.F=g.SE((0,g.A)(function(){this.G()},this),100)};
g.h.QM=function(a,b,c){nFa(this.J,this.H.receiver.label,a,this.A.friendlyName,(0,g.A)(function(a){a&&a.token?(this.Dq(a),b(new chrome.cast.DialLaunchResponse(!1))):this.Vu(b,c)},this),(0,g.A)(function(a){t7(this,"Failed to get DIAL screen: "+a);
this.Vu(b,c)},this))};g.B(w7,s7);w7.prototype.stop=function(){this.De()};
w7.prototype.rx=g.z;w7.prototype.vk=function(){g.UE(this.o);this.o=NaN;var a=m6(this.J.ye(),this.A.label);a?this.Dq(a):this.De(Error("No such screen"))};
w7.prototype.W=function(){g.UE(this.o);this.o=NaN;w7.ga.W.call(this)};g.B(x7,g.V);g.h=x7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new chrome.cast.ApiConfig(c,(0,g.A)(this.LE,this),(0,g.A)(this.rT,this),d,e);c.customDialLaunchCallback=(0,g.A)(this.nR,this);chrome.cast.initialize(c,(0,g.A)(function(){this.la()||
(chrome.cast.addReceiverActionListener(this.C),aFa(),this.A.subscribe("onlineScreenChange",(0,g.A)(this.cH,this)),this.B=vFa(this),chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(a){this.tc("Failed to set initial custom receivers: "+g.Vg(a))},this)),this.V("yt-remote-cast2-availability-change",z7(this)),b(!0))},this),(0,g.A)(function(a){this.tc("Failed to initialize API: "+g.Vg(a));
b(!1)},this))};
g.h.JV=function(a,b){y7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.B;if(!a||c&&c.id!=a)y7("Unsetting old screen status: "+this.o.A.friendlyName),A7(this,null)}if(a&&b){if(!this.o){c=m6(this.A.ye(),a);if(!c){y7("setConnectedScreenStatus: Unknown screen.");return}var d=uFa(this,c);d||(y7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.B.push(d),chrome.cast.setCustomReceivers(this.B,
g.z,(0,g.A)(function(a){this.tc("Failed to set initial custom receivers: "+g.Vg(a))},this)));
y7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);A7(this,new w7(this.A,d),!0)}this.o.tx(b)}else y7("setConnectedScreenStatus: no screen.")};
g.h.KV=function(a){this.la()?this.tc("Setting connection data on disposed cast v2"):this.o?this.o.vk(a):this.tc("Setting connection data without a session")};
g.h.NW=function(){this.la()?this.tc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),A7(this,null)):y7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.A)(this.LE,this),(0,g.A)(this.OT,this))};
g.h.W=function(){this.A.unsubscribe("onlineScreenChange",(0,g.A)(this.cH,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.C);g.$a(g.w("yt.mdx.remote.debug.handlers_")||[],YEa);g.Bf(this.o);x7.ga.W.call(this)};
g.h.tc=function(a){c7("Controller",a)};
g.h.ME=function(a,b){this.o==a&&(b||A7(this,null),this.V("yt-remote-cast2-session-change",b))};
g.h.nT=function(a,b){if(!this.la())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),y7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)y7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{y7("onReceiverAction_: Casting to active receiver.");this.o.B&&this.V("yt-remote-cast2-session-change",this.o.B);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:A7(this,
new w7(this.A,a));break;case chrome.cast.ReceiverType.DIAL:A7(this,new v7(this.A,a,this.F));break;case chrome.cast.ReceiverType.CAST:A7(this,new u7(this.A,a));break;default:this.tc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.tc("Stopping receiver w/o session: "+a.friendlyName)}else this.tc("onReceiverAction_ called without receiver.")};
g.h.nR=function(a){if(this.la())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.tc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.tc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.B)return y7("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.o.B),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.tc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);A7(this,new v7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.A)(b.QM,b,(b.H.extraData||{}).screenId||null)):new Promise((0,g.A)(b.Vu,b))};
g.h.LE=function(a){if(!this.la()){y7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)y7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),A7(this,new u7(this.A,b),!0);else{this.tc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=m6(this.A.ye(),c.label);d&&h6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(y7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Bf(this.o),this.o=new u7(this.A,b),this.o.subscribe("sessionScreen",(0,g.A)(this.ME,this,this.o)),this.o.vk(null));this.o.rx(a)}}};
g.h.MW=function(){return this.o?this.o.dH():null};
g.h.OT=function(a){this.la()||(this.tc("Failed to estabilish a session: "+g.Vg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&A7(this,null))};
g.h.rT=function(a){y7("Receiver availability updated: "+a);if(!this.la()){var b=z7(this);this.D=a==chrome.cast.ReceiverAvailability.AVAILABLE;z7(this)!=b&&this.V("yt-remote-cast2-availability-change",z7(this))}};
g.h.cH=function(){this.la()||(this.B=vFa(this),y7("Updating custom receivers: "+g.Vg(this.B)),chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(){this.tc("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",z7(this)))};
x7.prototype.setLaunchParams=x7.prototype.KV;x7.prototype.setConnectedScreenStatus=x7.prototype.JV;x7.prototype.stopSession=x7.prototype.NW;x7.prototype.getCastSession=x7.prototype.MW;x7.prototype.requestSession=x7.prototype.requestSession;x7.prototype.init=x7.prototype.init;x7.prototype.dispose=x7.prototype.dispose;var G7=[];g.h=L7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";M7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.Yf=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.A=a.seekableEnd,this.H=a.duration,this.J=a.loadedTime,this.B=a.liveIngestionTime,this.D=!isNaN(this.B))};
g.h.tb=function(){return 1==this.playerState};
g.h.isAdPlaying=function(){return 1081==this.playerState};
g.h.getDuration=function(){return this.D?this.H+N7(this):this.H};
g.h.clone=function(){return new L7(R7(this))};g.B(T7,g.V);g.h=T7.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.z,Z7(this,"play")):Y7(this,"play"),X7(this,1,P7(U7(this))),this.V("remotePlayerChange")):V7(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.z,Z7(this,"pause")):Y7(this,"pause"),X7(this,2,P7(U7(this))),this.V("remotePlayerChange")):V7(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.A){var b=U7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.tb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.z,Z7(this,"seekTo",{newTime:a}))}else Y7(this,"seekTo",{newTime:a});X7(this,3,a);this.V("remotePlayerChange")}else V7(this,g.La(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.z,Z7(this,"stopVideo")):Y7(this,"stopVideo");var a=U7(this);a.index=-1;a.videoId="";M7(a);W7(this,a);this.V("remotePlayerChange")}else V7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=U7(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.A)(function(){c7("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.tc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.A)(function(){c7("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.tc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);Y7(this,"setVolume",e)}c.muted=b;c.volume=a;W7(this,c)}else V7(this,g.La(this.setVolume,a,b))};
g.h.XF=function(a,b){if(1==this.o){var c=U7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Vg(b.style),g.jc(d,c.o));Y7(this,"setSubtitlesTrack",d);W7(this,c)}else V7(this,g.La(this.XF,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){Y7(this,"setAudioTrack",{videoId:a,audioTrackId:b.Ob.id});var c=U7(this);c.audioTrackId=b.Ob.id;W7(this,c)}else V7(this,g.La(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=U7(this);c=c||0;var m={videoId:a,currentIndex:c};Q7(l,a,c);g.za(b)&&(O7(l,b),m.currentTime=b);g.za(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Vg(k));Y7(this,"setPlaylist",m);d||W7(this,l)};
g.h.Jq=function(a,b){if(1==this.o){if(a&&b){var c=U7(this);Q7(c,a,b);W7(this,c)}Y7(this,"previous")}else V7(this,g.La(this.Jq,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=U7(this);Q7(c,a,b);W7(this,c)}Y7(this,"next")}else V7(this,g.La(this.nextVideo,a,b))};
g.h.EA=function(){1==this.o?Y7(this,"dismissAutoplay"):V7(this,this.EA)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.V("proxyStateChange",a,this.o)}T7.ga.dispose.call(this)};
g.h.W=function(){IFa(this);this.C=null;this.D.clear();S7(this,null);T7.ga.W.call(this)};
g.h.ty=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.rD(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.iT=function(a,b){this.V(a,b)};
g.h.MQ=function(a){if(!a)this.wn(null),S7(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=U7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)c7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,W7(this,b)}};
g.h.wn=function(a){c7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),JFa(this),this.V("remotePlayerChange")};
g.h.LQ=function(a){a?(JFa(this),this.V("remotePlayerChange")):this.wn(null)};
g.h.Ix=function(){Y7(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.YQ=function(){var a=FFa();a&&S7(this,a)};
g.h.tc=function(a){c7("CP",a)};g.B($7,g.V);g.h=$7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.za(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.za(k)&&(l.currentIndex=k);c&&(this.qb.listId=c);this.qb.videoId=d;this.qb.index=k||0;this.qb.state=3;O7(this.qb,m);this.C="UNSUPPORTED";a8("Connecting with setPlaylist and params: "+g.Vg(l));this.o.connect({method:"setPlaylist",
params:g.Vg(l)},a,hEa())}else a8("Connecting without params"),this.o.connect({},a,hEa());LFa(this)};
g.h.dispose=function(){this.la()||(this.V("beforeDispose"),b8(this,3));$7.ga.dispose.call(this)};
g.h.W=function(){c8(this);e8(this);d8(this);g.UE(this.J);this.J=NaN;g.UE(this.K);this.K=NaN;this.B=null;g.GG(this.T);this.T.length=0;this.o.dispose();$7.ga.W.call(this);this.C=this.G=this.A=this.qb=this.o=null};
g.h.gL=function(){this.F(2)};
g.h.QQ=function(){a8("Channel opened");this.N&&(this.N=!1,d8(this),this.R=g.SE((0,g.A)(function(){a8("Timing out waiting for a screen.");this.F(1)},this),15E3));
lEa(VEa(this.o),this.aa)};
g.h.NQ=function(){a8("Channel closed");isNaN(this.D)?r6(!0):r6();this.dispose()};
g.h.OQ=function(a){r6();isNaN(this.H())?(a8("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,a8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),b8(this,2))};
g.h.PQ=function(a){a.params?a8("Received: action="+a.action+", params="+g.Vg(a.params)):a8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Zx(a.params.devices);this.A=(0,g.I)(a,function(a){return new f6(a)});
a=!!g.Ra(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
OFa(this,a);break;case "loungeScreenDisconnected":g.ab(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
OFa(this,!1);break;case "remoteConnected":var b=new f6(g.Zx(a.params.device));g.Ra(this.A,function(a){return b?a.id==b.id:!1})||g.Ya(this.A,b);
break;case "remoteDisconnected":b=new f6(g.Zx(a.params.device));g.ab(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":QFa(this,a);break;case "nowPlaying":SFa(this,a);break;case "onStateChange":RFa(this,a);break;case "onAdStateChange":TFa(this,a);break;case "onVolumeChanged":UFa(this,a);break;case "onSubtitlesTrackChanged":PFa(this,a);break;case "nowAutoplaying":VFa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.V("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.V("autoplayModeChange",this.C);"DISABLED"==this.C&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":WFa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:a8("Unrecognized action: "+a.action)}};
g.h.qV=function(){if(this.B){var a=this.B;this.B=null;this.qb.videoId!=a&&f8(this,"getNowPlaying")}};
$7.prototype.subscribe=$7.prototype.subscribe;$7.prototype.unsubscribeByKey=$7.prototype.zk;$7.prototype.ha=function(){var a=3;this.la()||(a=0,isNaN(this.H())?Y6(this.o)&&isNaN(this.D)&&(a=1):a=2);return a};
$7.prototype.getProxyState=$7.prototype.ha;$7.prototype.F=function(a){a8("Disconnecting with "+a);c8(this);this.V("beforeDisconnect",a);1==a&&r6();WEa(this.o,a);this.dispose()};
$7.prototype.disconnect=$7.prototype.F;$7.prototype.fa=function(){var a=this.qb;this.B&&(a=this.qb.clone(),Q7(a,this.B,a.index));return R7(a)};
$7.prototype.getPlayerContextData=$7.prototype.fa;
$7.prototype.ma=function(a){var b=new L7(a);b.videoId&&b.videoId!=this.qb.videoId&&(this.B=b.videoId,g.UE(this.J),this.J=g.SE((0,g.A)(this.qV,this),5E3));var c=[];this.qb.listId==b.listId&&this.qb.videoId==b.videoId&&this.qb.index==b.index||c.push("remoteQueueChange");this.qb.playerState==b.playerState&&this.qb.volume==b.volume&&this.qb.muted==b.muted&&P7(this.qb)==P7(b)&&g.Vg(this.qb.o)==g.Vg(b.o)||c.push("remotePlayerChange");this.qb.reset(a);(0,g.C)(c,function(a){this.V(a)},this)};
$7.prototype.setPlayerContextData=$7.prototype.ma;$7.prototype.Z=function(){var a=this.o.F.id,b=g.Ra(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
$7.prototype.getOtherConnectedRemoteId=$7.prototype.Z;$7.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.H)():NaN};
$7.prototype.getReconnectTimeout=$7.prototype.H;$7.prototype.ea=function(){return this.C||"UNSUPPORTED"};
$7.prototype.getAutoplayMode=$7.prototype.ea;$7.prototype.da=function(){return this.G||""};
$7.prototype.getAutoplayVideoId=$7.prototype.da;$7.prototype.ya=function(){if(!isNaN(this.H())){var a=this.o.A;g.dv(a.o);a.start()}};
$7.prototype.reconnect=$7.prototype.ya;$7.prototype.ka=function(a,b){f8(this,a,b);NFa(this)};
$7.prototype.sendMessage=$7.prototype.ka;g.B(g8,g7);g.h=g8.prototype;g.h.ye=function(a){return this.ld.$_gs(a)};
g.h.contains=function(a){return!!this.ld.$_c(a)};
g.h.get=function(a){return this.ld.$_g(a)};
g.h.start=function(){this.ld.$_st()};
g.h.add=function(a,b,c){this.ld.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.ld.$_r(a,b,c)};
g.h.Lr=function(a,b,c,d){this.ld.$_un(a,b,c,d)};
g.h.W=function(){for(var a=0,b=this.A.length;a<b;++a)this.ld.$_ubk(this.A[a]);this.A.length=0;this.ld=null;g8.ga.W.call(this)};
g.h.JW=function(){this.V("screenChange")};
g.h.HS=function(){this.V("onlineScreenChange")};
p7.prototype.$_st=p7.prototype.start;p7.prototype.$_gspc=p7.prototype.KW;p7.prototype.$_gsppc=p7.prototype.bH;p7.prototype.$_c=p7.prototype.contains;p7.prototype.$_g=p7.prototype.get;p7.prototype.$_a=p7.prototype.add;p7.prototype.$_un=p7.prototype.Lr;p7.prototype.$_r=p7.prototype.remove;p7.prototype.$_gs=p7.prototype.ye;p7.prototype.$_gos=p7.prototype.aH;p7.prototype.$_s=p7.prototype.subscribe;p7.prototype.$_ubk=p7.prototype.zk;var h8=null,i8=null,x8=null,m8=[];g.r(y8,g.J);g.h=y8.prototype;
g.h.W=function(){g.J.prototype.W.call(this);this.C.stop();this.F.stop();this.L.stop();this.N();this.o.unsubscribe("proxyStateChange",this.IE,this);this.o.unsubscribe("remotePlayerChange",this.zn,this);this.o.unsubscribe("remoteQueueChange",this.Eq,this);this.o.unsubscribe("autoplayUpNext",this.fE,this);this.o.unsubscribe("previousNextChange",this.FE,this);this.o.unsubscribe("nowAutoplaying",this.xE,this);this.o.unsubscribe("autoplayDismissed",this.eE,this);this.o=this.D=null};
g.h.gD=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(B8(this)){if(!U7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":U7(this.o).tb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.K.zm(c[0],c[1]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.o.setAudioTrack(this.A.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.A.getCurrentTime();D8(this,0==c?void 0:c);break;case "control_seek":D8(this,c[0]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.o.setAudioTrack(this.A.getVideoData(1).videoId,c)}};
g.h.KQ=function(a){this.L.bL(a)};
g.h.lW=function(a){this.gD("control_subtitles_set_track",g.bc(a)?null:a)};
g.h.nG=function(){var a=this.A.getOption("captions","track");g.bc(a)||C8(this,a)};
g.h.tE=function(a){if(B8(this)){this.o.unsubscribe("remotePlayerChange",this.zn,this);var b=Math.round(a.volume);a=!!a.muted;var c=U7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.R.start();this.o.subscribe("remotePlayerChange",this.zn,this)}};
g.h.bS=function(){g.bc(this.G)||hGa(this,this.G);this.H=!1};
g.h.IE=function(a,b){this.F.stop();2==b&&this.lG()};
g.h.zn=function(){if(B8(this)){this.C.stop();var a=U7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.D.Xk(1);break;case 1082:case 1083:this.D.Xk(0);break;default:this.D.Xk(-1)}switch(a.playerState){case 1081:case 1:A8(this,new g.MQ(8));this.kG();break;case 1085:case 3:A8(this,new g.MQ(9));break;case 1083:case 0:A8(this,new g.MQ(2));this.K.stop();z8(this,this.A.getVideoData().lengthSeconds);break;case 1084:A8(this,new g.MQ(4));break;case 2:A8(this,new g.MQ(4));z8(this,P7(a));
break;case -1:A8(this,new g.MQ(64));break;case -1E3:A8(this,new g.MQ(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=U7(this.o).o;var b=this.G;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.G=a,hGa(this,a));a=U7(this.o);-1==a.volume||Math.round(this.A.getVolume())==a.volume&&this.A.isMuted()==a.muted||this.R.isActive()||this.NG()}else gGa(this)};
g.h.FE=function(){this.A.V("mdxpreviousnextchange")};
g.h.Eq=function(){B8(this)||gGa(this)};
g.h.cK=function(){this.o.EA()};
g.h.fE=function(a){a&&(a=g.DF("/watch_queue_ajax",{method:"GET",gd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.A)(this.qU,this)}))&&(this.N=(0,g.A)(a.abort,a))};
g.h.qU=function(a,b){var c=new g.GP(g.Y(this.A),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.A.V("mdxautoplayupnext",c)};
g.h.xE=function(a){isNaN(a)||this.A.V("mdxnowautoplaying",a)};
g.h.eE=function(){this.A.V("mdxautoplaycanceled")};
g.h.EO=function(a,b){-1==U7(this.o).playerState?D8(this,a):b&&this.o.seekTo(a)};
g.h.NG=function(){if(B8(this)){var a=U7(this.o);this.B.La(this.T);a.muted?this.A.mute():this.A.unMute();this.A.setVolume(a.volume);this.T=this.B.O(this.A,"onVolumeChange",this.tE)}};
g.h.kG=function(){this.C.stop();if(!this.o.la()){var a=U7(this.o);a.tb()&&A8(this,new g.MQ(8));z8(this,P7(a));this.C.start()}};
g.h.lG=function(){this.F.stop();this.C.stop();var a=this.o.C.getReconnectTimeout();2==this.o.o&&!isNaN(a)&&this.F.start()};g.r(E8,g.W);E8.prototype.D=function(a){jGa(this,a.state)};g.r(F8,g.cX);F8.prototype.L=function(){var a=this.B.getOption("remote","receivers");a&&1<a.length&&!this.B.getOption("remote","quickCast")?(this.H=g.tb(a,this.F,this),g.dX(this,(0,g.I)(a,this.F)),a=this.B.getOption("remote","currentReceiver"),this.zf(this.F(a)),this.enable(!0)):this.enable(!1)};
F8.prototype.F=function(a){return a.key};
F8.prototype.yf=function(a){return"cast-selector-receiver"==a?"Cast...":this.H[a].name};
F8.prototype.Hd=function(a){g.cX.prototype.Hd.call(this,a);this.B.setOption("remote","currentReceiver",this.H[a]);this.C.Kb()};g.r(G8,g.oV);g.h=G8.prototype;g.h.create=function(){aGa(g.yN(g.Y(this.player)));this.D.push(g.ZE("yt-remote-before-disconnect",this.GQ,this));this.D.push(g.ZE("yt-remote-connection-change",this.sT,this));this.D.push(g.ZE("yt-remote-receiver-availability-change",this.GE,this));this.D.push(g.ZE("yt-remote-auto-connect",this.qT,this));this.D.push(g.ZE("yt-remote-receiver-resumed",this.pT,this));this.GE()};
g.h.load=function(){this.player.cancelPlayback();g.oV.prototype.load.call(this);this.C=new y8(this,this.player,this.o);var a=(a=fGa())?a.currentTime:0;var b=w8()?new T7(r8(),void 0):null;0==a&&b&&(a=P7(U7(b)));0!=a&&this.Ie(a);iGa(this,this.gn,this.gn);g.D0(this.player.app,6)};
g.h.unload=function(){this.player.V("mdxautoplaycanceled");this.B=this.A;g.Cf(this.C,this.o);this.o=this.C=null;g.oV.prototype.unload.call(this);g.D0(this.player.app,5)};
g.h.W=function(){g.$E(this.D);g.oV.prototype.W.call(this)};
g.h.Xh=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.gD.apply(this.C,[a].concat(g.ea(c)))};
g.h.Xk=function(a){this.H=a};
g.h.getAdState=function(){return this.H};
g.h.VK=function(){return this.loaded?this.C.suggestion:null};
g.h.Yf=function(){return this.o?U7(this.o).Yf:!1};
g.h.hasNext=function(){return this.o?U7(this.o).hasNext:!1};
g.h.Ie=function(a,b){this.J=a||0;this.player.V("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.J};
g.h.getProgressState=function(){var a=U7(this.o),b=this.player.getVideoData();return{allowSeeking:g.Y(this.player).experiments.o("web_player_mdx_allow_seeking_change_killswitch")?this.player.Nc():!a.isAdPlaying()&&this.player.Nc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.D?a.B+N7(a):a.B,isPeggedToLive:1>=(a.D?a.A+N7(a):a.A)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.D?a.A+N7(a):a.A,seekableStart:0<a.C?a.C+
N7(a):a.C}};
g.h.nextVideo=function(){this.o&&this.o.nextVideo()};
g.h.Jq=function(){this.o&&this.o.Jq()};
g.h.GQ=function(a){1==a&&(this.G=this.o?U7(this.o):null)};
g.h.sT=function(){var a=w8()?new T7(r8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.G=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Bf(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.G)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,P7(a)));this.player.V("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.GE=function(){this.F=[this.A].concat(cGa());var a=s8()||this.A;H8(this,a);this.player.Ba("onMdxReceiversChange")};
g.h.qT=function(){var a=s8();H8(this,a)};
g.h.pT=function(){this.B=s8()};
g.h.Jc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?J7():H8(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&J7(),!0):!1}};
g.h.Ix=function(){this.o.Ix()};
g.h.wc=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.WZ.remote=G8;})(_yt_player);
